### ISSUE TITLE
single api call in _app.js

### ISSUE THREAD

**Issue by MeghanHughes** [WhareHauora/App#96]
Need this in order to make PWA proper and work offline

**Comment by anna-marie-vos** [comment]
I'm working on this now.

**Comment by anna-marie-vos** [comment]
I've added a new branch [av/_appjs](https://github.com/WhareHauora/App/blob/av/_appjs/pages/_app.js)
I've create a new component in _app.js called "Layout" in which I make the API call and populate the props line 19-66. I did this because I was having trouble to get the 'req' variable.  
`Layout.getInitialProps = async function ({ req }) {...}`
I want to do [this](https://medium.com/@ruthmpardee/passing-data-between-react-components-103ad82ebd17)
The next step is to create a callback function in `export default class MyApp extends App` component, in which I can assign the props from Layout to the state of MyApp.  I've called it `this.getData = (data) => {...}`
I'm passing the getData function as a prop to the Layout component, however if a call the function in the Layout component it causes an infinite loop. 
In my last revision I've moved the getData function into the `Layout.getInitialProps = async function ({ req }) {...}` but now it's not triggering.

**Comment by anna-marie-vos** [comment]
the previous attempt did not work well with the async way next.js loads pages and handles frontend / server side rendering. 
The latest attempt: add the API call in _app.js 
`static async getInitialProps ({ Component, router, ctx }) {
>>>>insert here
}`
using `ctx.req` to access the request. 
and then once the call successfully made, using the following modules:
`import {createStore} from "redux";
import {Provider} from "react-redux";
import withRedux from "next-redux-wrapper";`
and using it according to [this](https://www.npmjs.com/package/next-redux-wrapper) 

but somewhere it breaks

**Comment by MeghanHughes** [comment]
Relevant branch = https://github.com/WhareHauora/App/tree/mh/reinstateSW

**Comment by anna-marie-vos** [comment]
To test it you have to comment out the API call at Dashboard and change some code so ot to get errors.
